#!/bin/bash
# Builds Wipeout.app from the .swift files next to this script.
#   ./build.sh                 -> ./build/Wipeout.app  (Apple Silicon)
#   INSTALL=1 ./build.sh       -> also copies the bundle to ~/Applications
set -euo pipefail

cd "$(dirname "$0")"

# ==============================================================
VERSION="0.2.10"     # <-- BUMP THIS each change
#   patch +1  small change or fix
#   minor +1  new feature, reset patch to 10
# ==============================================================

BIN_NAME="Wipeout"
APP_NAME="Wipeout.app"
BUNDLE_ID="co.dataspike.wipeout"
MIN_MACOS="13.0"
AUTHOR="Andy Rostad"
COPYRIGHT="Copyright (c) 2026 Andy Rostad — MIT License"
GITHUB_URL="https://github.com/arostad"
GITHUB_HANDLE="@arostad"
BUILD_DIR="build"
APP_DIR="${BUILD_DIR}/${APP_NAME}"

command -v swiftc >/dev/null || { echo "swiftc not found - install Xcode Command Line Tools: xcode-select --install"; exit 1; }

cat > Version.swift <<VERSRC
// Generated by build.sh - do not edit.
enum BuildInfo {
    static let version = "${VERSION}"
    static let author = "${AUTHOR}"
    static let copyright = "${COPYRIGHT}"
    static let githubURL = "${GITHUB_URL}"
    static let githubHandle = "${GITHUB_HANDLE}"
}
VERSRC

SOURCES=(Disk.swift FormatRunner.swift UpdateChecker.swift UI.swift Version.swift)
for f in "${SOURCES[@]}"; do
  [ -f "$f" ] || { echo "missing source: $f"; exit 1; }
done

rm -rf "$BUILD_DIR"
mkdir -p "${APP_DIR}/Contents/MacOS" "${APP_DIR}/Contents/Resources"

compile() {
  local arch="$1" out="$2"
  echo "compiling ${arch}..."
  swiftc -O -parse-as-library \
    -target "${arch}-apple-macos${MIN_MACOS}" \
    -o "$out" "${SOURCES[@]}"
}

compile arm64 "${APP_DIR}/Contents/MacOS/${BIN_NAME}"

cat > "${APP_DIR}/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>Wipeout</string>
    <key>CFBundleDisplayName</key><string>Wipeout</string>
    <key>CFBundleExecutable</key><string>${BIN_NAME}</string>
    <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>${VERSION}</string>
    <key>CFBundleVersion</key><string>${VERSION}</string>
    <key>LSMinimumSystemVersion</key><string>${MIN_MACOS}</string>
    <key>NSHumanReadableCopyright</key><string>${COPYRIGHT}</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSPrincipalClass</key><string>NSApplication</string>
</dict>
</plist>
PLIST

printf 'APPL????' > "${APP_DIR}/Contents/PkgInfo"

if [ -f resources/Shell.efi ]; then
  cp resources/Shell.efi "${APP_DIR}/Contents/Resources/Shell.efi"
  echo "UEFI shell payload bundled"
else
  echo "note: resources/Shell.efi missing - the UEFI shell format option will be disabled"
fi

if [ -d icon/AppIcon.iconset ] && command -v iconutil >/dev/null; then
  iconutil -c icns icon/AppIcon.iconset -o "${APP_DIR}/Contents/Resources/AppIcon.icns"
  echo "icon built from iconset via iconutil"
elif [ -f icon/AppIcon.icns ]; then
  cp icon/AppIcon.icns "${APP_DIR}/Contents/Resources/AppIcon.icns"
  echo "icon copied from prebuilt icns"
else
  echo "warning: no icon found - bundle will use the generic app icon"
fi

if [ -n "${SIGN_ID:-}" ]; then
  codesign --force --sign "${SIGN_ID}" "${APP_DIR}" && echo "signed with ${SIGN_ID}"
else
  codesign --force --sign - --timestamp=none "${APP_DIR}" >/dev/null 2>&1 \
    && echo "ad-hoc signed (signature changes each rebuild - see SIGN_ID)" \
    || echo "codesign skipped (unsigned bundle still runs locally)"
fi

echo "built: ${APP_DIR}  (v${VERSION})"

if [ "${INSTALL:-0}" = "1" ]; then
  mkdir -p "${HOME}/Applications"
  rm -rf "${HOME}/Applications/${APP_NAME}"
  cp -R "${APP_DIR}" "${HOME}/Applications/"
  echo "installed: ${HOME}/Applications/${APP_NAME}"
fi
